# Supabase PostgreSQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.dvyxnxcqilawsekviukd}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Lux@3015pcb}
spring.datasource.driverClassName=org.postgresql.Driver

# Hikari Connection Pool Settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=${SERVER_PORT:8082}

# CORS
spring.web.cors.enabled=true